os: linux
dist: focal
arch: amd64

language: go
go:
  - 1.14.x
  - 1.15.x
  - 1.16.x

services:
  - docker

before_install:
  - nvm install 14.16
  - nvm use 14.16

install:
  - go mod download -x
  - make install-ginkgo
  - make install-golangci-lint
  - npm install

script:
  - make all
